version: "3.7"
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "10"

services:
  nifi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nifi
    logging: *default-logging
    restart: always
    ports:
      - 8080:8080
    environment:
      TZ: ${TIMEZONE}
      #NIFI_WEB_HTTP_PORT: 9091
      #NIFI_WEB_HTTP_HOST: domain.com
      #NIFI_WEB_PROXY_CONTEXT_PATH: /nifi
